### ISSUE TITLE
Removal of the script

### ISSUE THREAD

**Issue by SAGEof6iixPATHS** [AVKorotkov/bulk-whois#1]
Hello!

Why did you remove the script??
I really need this... Can you push the script again?

**Comment by AVKorotkov** [comment]
Hey there,
I'm going to change this script, so I cleaned up it some time ago. I'll recreate it soon. Maybe next week.

**Comment by SAGEof6iixPATHS** [comment]
Can you give me the old script? I kind of need it now, it is urgent. I need to get on with my engagement ASAP.

**Comment by AVKorotkov** [comment]
Sorry, no. It's on my another PC that is currently under repair.

**Comment by SAGEof6iixPATHS** [comment]
Oh, okay.

**Comment by AVKorotkov** [comment]
The script is rewritten and does work correctly.
